"""Rootless Podman sandbox file rendering."""

from __future__ import annotations

import json
import shlex
import shutil
import subprocess
from pathlib import Path

from .models import ProjectConfig
from .templates import clean
from .toolchains import packages_for, unique


SANDBOX_EXECUTABLES: tuple[str, ...] = (
    "scripts/sandbox/doctor",
    "scripts/sandbox/build",
    "scripts/sandbox/shell",
    "scripts/sandbox/exec",
    "scripts/sandbox/check",
    "scripts/sandbox/logs",
    "scripts/sandbox/clean",
    "scripts/sandbox/codex",
    "scripts/sandbox/codex-login",
    "scripts/sandbox/resume",
    "scripts/sandbox/codex-exec",
    "scripts/sandbox/db-up",
    "scripts/sandbox/db-down",
    "scripts/sandbox/db-shell",
    "scripts/sandbox/db-logs",
    "scripts/sandbox/web",
    "scripts/sandbox/headless-test",
    "scripts/playtest-host",
)

CACHYOS_PODMAN_COMMAND = "sudo pacman -S --needed podman passt fuse-overlayfs"
SANDBOX_ENV_MARKER = "AGENTKIT_INSIDE_SANDBOX=1"
HOST_SIDE_SANDBOX_MESSAGE = "This is a host-side sandbox command. Exit the container and run it from the project root on the host."


def project_id(config: ProjectConfig) -> str:
    slug = config.project_slug or "project"
    return "".join(character if character.isalnum() else "-" for character in slug.lower()).strip("-") or "project"


def image_name(config: ProjectConfig) -> str:
    return f"agentkit-{project_id(config)}:dev"


def volume_name(config: ProjectConfig, suffix: str) -> str:
    return f"agentkit_{project_id(config)}_{suffix}"


def sandbox_json(config: ProjectConfig) -> str:
    payload = {
        "schema_version": 1,
        "engine": "podman",
        "mode": config.sandbox.mode,
        "rootless_required": config.sandbox.rootless_required,
        "codex_inside_container": config.sandbox.codex_inside_container,
        "workspace_mount": "/workspace",
        "image": image_name(config),
        "volumes": {
            "cache": volume_name(config, "cache"),
            "codex_home": volume_name(config, "codex_home"),
            "db_data": volume_name(config, "db_data"),
        },
        "mount_policy": {
            "project_workspace": "rw",
            "host_home": "not-mounted",
            "host_codex_home": "not-mounted",
            "host_ssh": "not-mounted",
            "host_browser_profiles": "not-mounted",
            "host_git_credentials": "not-mounted",
        },
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def containerfile(config: ProjectConfig) -> str:
    packages = unique(packages_for(config.languages, config.database, github=False))
    if config.sandbox.codex_inside_container:
        packages.extend(["nodejs", "npm"])
    install = " ".join(shlex.quote(package) for package in unique(packages))
    codex_note = (
        "\n# Codex CLI is installed only for explicit codex-inside-container mode.\n"
        "RUN npm install -g @openai/codex\n"
        if config.sandbox.codex_inside_container
        else ""
    )
    return clean(
        f"""
        # Generated by CLI AI Agent Starter Kit.
        # Arch Linux is used because the primary host target is CachyOS/Arch and package names stay reviewable.
        FROM docker.io/library/archlinux:base-devel

        RUN pacman -Syu --noconfirm --needed {install} \\
            && pacman -Scc --noconfirm
        RUN useradd -m -u 1000 codex
        {codex_note}
        WORKDIR /workspace
        USER codex
        """
    )


def _inside_sandbox_helper() -> str:
    return clean(
        """
        inside_agentkit_sandbox() {
          test "${AGENTKIT_INSIDE_SANDBOX:-}" = "1" && return 0
          test -f /run/.containerenv && return 0
          test -f /.dockerenv && return 0
          return 1
        }
        """
    )


def _host_side_guard() -> str:
    return (
        _inside_sandbox_helper()
        + "\n"
        + clean(
            f"""
            if inside_agentkit_sandbox; then
              printf '%s\\n' {shlex.quote(HOST_SIDE_SANDBOX_MESSAGE)}
              exit 2
            fi
            """
        )
    )


def _script_prelude(config: ProjectConfig) -> str:
    return clean(
        f"""
        #!/usr/bin/env sh
        set -eu
        ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
        IMAGE={shlex.quote(image_name(config))}
        WORKSPACE=/workspace
        CACHE_VOLUME={shlex.quote(volume_name(config, "cache"))}
        CODEX_HOME_VOLUME={shlex.quote(volume_name(config, "codex_home"))}
        DB_VOLUME={shlex.quote(volume_name(config, "db_data"))}

        {_inside_sandbox_helper()}

        run_project_container() {{
          podman run --rm \\
            --env AGENTKIT_INSIDE_SANDBOX=1 \\
            --volume "$ROOT:/workspace:Z" \\
            --volume "$CACHE_VOLUME:/home/codex/.cache:Z" \\
            --workdir /workspace \\
            "$IMAGE" "$@"
        }}
        """
    )


def doctor_script(config: ProjectConfig) -> str:
    return clean(
        f"""
        #!/usr/bin/env sh
        set -eu
        ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
        {_host_side_guard()}
        printf '%s\\n' 'Agent Kit rootless Podman sandbox doctor'
        if ! command -v podman >/dev/null 2>&1; then
          printf '%s\\n' '[missing] podman'
          printf 'Review on CachyOS: %s\\n' {shlex.quote(CACHYOS_PODMAN_COMMAND)}
          exit 2
        fi
        podman info >/dev/null
        if podman info --format '{{{{.Host.Security.Rootless}}}}' 2>/dev/null | grep -qi true; then
          printf '%s\\n' '[ok] Podman reports rootless mode.'
        else
          printf '%s\\n' '[warn] Could not confirm rootless mode from podman info.'
        fi
        USER_NAME=$(id -un)
        grep -q "^${{USER_NAME}}:" /etc/subuid 2>/dev/null && printf '%s\\n' '[ok] /etc/subuid has a mapping for this user.' || printf '%s\\n' '[warn] /etc/subuid mapping not found or not inspectable.'
        grep -q "^${{USER_NAME}}:" /etc/subgid 2>/dev/null && printf '%s\\n' '[ok] /etc/subgid has a mapping for this user.' || printf '%s\\n' '[warn] /etc/subgid mapping not found or not inspectable.'
        command -v pasta >/dev/null 2>&1 || command -v passt >/dev/null 2>&1 || printf '%s\\n' '[warn] passt/pasta not found; rootless networking may be limited.'
        command -v fuse-overlayfs >/dev/null 2>&1 || printf '%s\\n' '[warn] fuse-overlayfs not found; Podman may use another storage driver.'
        test -f "$ROOT/.agent-starter/sandbox/sandbox.json" && printf '%s\\n' '[ok] sandbox config exists.'
        podman image exists {shlex.quote(image_name(config))} && printf '%s\\n' '[ok] sandbox image exists.' || printf '%s\\n' '[info] sandbox image needs build: scripts/sandbox/build'
        """
    )


def build_script(config: ProjectConfig) -> str:
    return clean(
        f"""
        #!/usr/bin/env sh
        set -eu
        ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
        {_host_side_guard()}
        podman build -t {shlex.quote(image_name(config))} -f "$ROOT/.agent-starter/sandbox/Containerfile" "$ROOT"
        """
    )


def shell_script(config: ProjectConfig) -> str:
    return _script_prelude(config) + clean(
        """

        if inside_agentkit_sandbox; then
          exec /bin/sh
        fi

        run_interactive_project_container() {
          podman run --rm -it \\
            --env AGENTKIT_INSIDE_SANDBOX=1 \\
            --volume "$ROOT:/workspace:Z" \\
            --volume "$CACHE_VOLUME:/home/codex/.cache:Z" \\
            --workdir /workspace \\
            "$IMAGE" "$@"
        }

        run_interactive_project_container /bin/sh
        """
    )


def exec_script(config: ProjectConfig) -> str:
    return _script_prelude(config) + clean(
        """

        if inside_agentkit_sandbox; then
          if [ "$#" -eq 0 ]; then
            printf '%s\\n' 'Already inside the Agent Kit sandbox. No command was provided.'
            exit 2
          fi
          exec "$@"
        fi

        run_project_container "$@"
        """
    )


def check_script(config: ProjectConfig) -> str:
    return _script_prelude(config) + clean(
        """

        if inside_agentkit_sandbox; then
          printf '%s\\n' 'Already inside the Agent Kit sandbox. Running ./scripts/check.sh directly.'
          exec ./scripts/check.sh
        fi

        run_project_container ./scripts/check.sh
        """
    )


def logs_script(config: ProjectConfig) -> str:
    return clean(
        f"""
        #!/usr/bin/env sh
        set -eu
        {_host_side_guard()}
        podman ps -a --filter name={shlex.quote('agentkit-' + project_id(config))}
        """
    )


def clean_script(config: ProjectConfig) -> str:
    return clean(
        f"""
        #!/usr/bin/env sh
        set -eu
        {_host_side_guard()}
        printf '%s\\n' 'This removes stopped sandbox containers only. Volumes are preserved.'
        podman container prune --filter label=agentkit.project={shlex.quote(project_id(config))}
        printf '%s\\n' 'To remove project volumes manually, review:'
        printf '  podman volume rm %s %s %s\\n' {shlex.quote(volume_name(config, "cache"))} {shlex.quote(volume_name(config, "codex_home"))} {shlex.quote(volume_name(config, "db_data"))}
        """
    )


def codex_script(config: ProjectConfig) -> str:
    base = _script_prelude(config)
    run = (
        'if inside_agentkit_sandbox; then\n'
        "  printf '%s\\n' "
        + shlex.quote(HOST_SIDE_SANDBOX_MESSAGE)
        + "\n"
        "  exit 2\n"
        "fi\n"
        'podman run --rm -it --name agentkit-'
        + project_id(config)
        + '-codex --env AGENTKIT_INSIDE_SANDBOX=1 --volume "$ROOT:/workspace:Z" --volume "$CODEX_HOME_VOLUME:/home/codex:Z" '
        '--workdir /workspace '
        + shlex.quote(image_name(config))
        + ' codex --sandbox workspace-write --ask-for-approval on-request\n'
    )
    return base + "\n" + run


def codex_login_script(config: ProjectConfig) -> str:
    return (
        _script_prelude(config)
        + "\n"
        + _host_side_guard()
        + '\npodman run --rm -it --env AGENTKIT_INSIDE_SANDBOX=1 --volume "$ROOT:/workspace:Z" --volume "$CODEX_HOME_VOLUME:/home/codex:Z" --workdir /workspace '
        + shlex.quote(image_name(config))
        + " codex login --device-auth\n"
    )


def resume_script(config: ProjectConfig) -> str:
    return (
        _script_prelude(config)
        + "\n"
        + _host_side_guard()
        + '\npodman run --rm -it --env AGENTKIT_INSIDE_SANDBOX=1 --volume "$ROOT:/workspace:Z" --volume "$CODEX_HOME_VOLUME:/home/codex:Z" --workdir /workspace '
        + shlex.quote(image_name(config))
        + " codex resume --last\n"
    )


def codex_exec_script(config: ProjectConfig) -> str:
    return _script_prelude(config) + "\n" + _host_side_guard() + clean(
        f"""

        PROMPT_FILE=${{1:-FIRST_RUN_AUTONOMOUS.md}}
        test -f "$ROOT/$PROMPT_FILE"
        podman run --rm -i \\
          --env AGENTKIT_INSIDE_SANDBOX=1 \\
          --volume "$ROOT:/workspace:Z" \\
          --volume "$CODEX_HOME_VOLUME:/home/codex:Z" \\
          --workdir /workspace \\
          {shlex.quote(image_name(config))} \\
          codex exec --sandbox workspace-write --ask-for-approval never --cd /workspace - < "$ROOT/$PROMPT_FILE"
        """
    )


def env_sandbox_example(config: ProjectConfig) -> str:
    if config.database == "mariadb":
        return "SANDBOX_DB_NAME=app_dev\nSANDBOX_DB_USER=app_dev\nSANDBOX_DB_PASSWORD=dev_password_change_me\nSANDBOX_DB_PORT=3306\n"
    if config.database == "postgresql":
        return "SANDBOX_DB_NAME=app_dev\nSANDBOX_DB_USER=app_dev\nSANDBOX_DB_PASSWORD=dev_password_change_me\nSANDBOX_DB_PORT=5432\n"
    return ""


def db_scripts(config: ProjectConfig) -> dict[str, str]:
    if config.database not in {"mariadb", "postgresql"}:
        return {}
    is_mariadb = config.database == "mariadb"
    image = "docker.io/library/mariadb:latest" if is_mariadb else "docker.io/library/postgres:latest"
    name = f"agentkit-{project_id(config)}-{config.database}"
    volume = volume_name(config, "db_data")
    env_file = "--env-file .env.sandbox"
    port = "3306" if is_mariadb else "5432"
    data_path = "/var/lib/mysql" if is_mariadb else "/var/lib/postgresql/data"
    env_block = (
        "-e MARIADB_DATABASE=${SANDBOX_DB_NAME:-app_dev} \\\n"
        "  -e MARIADB_USER=${SANDBOX_DB_USER:-app_dev} \\\n"
        "  -e MARIADB_PASSWORD=${SANDBOX_DB_PASSWORD:-dev_password_change_me} \\\n"
        "  -e MARIADB_ROOT_PASSWORD=${SANDBOX_DB_PASSWORD:-dev_password_change_me}"
        if is_mariadb
        else "-e POSTGRES_DB=${SANDBOX_DB_NAME:-app_dev} \\\n"
        "  -e POSTGRES_USER=${SANDBOX_DB_USER:-app_dev} \\\n"
        "  -e POSTGRES_PASSWORD=${SANDBOX_DB_PASSWORD:-dev_password_change_me}"
    )
    up = clean(
        f"""
        #!/usr/bin/env sh
        set -eu
        {_host_side_guard()}
        test -f .env.sandbox || cp .env.sandbox.example .env.sandbox
        podman volume exists {shlex.quote(volume)} || podman volume create {shlex.quote(volume)}
        . ./.env.sandbox
        podman run -d --replace --name {shlex.quote(name)} {env_file} \\
          {env_block} \\
          -p 127.0.0.1:${{SANDBOX_DB_PORT:-{port}}}:{port} \\
          --volume {shlex.quote(volume)}:{data_path}:Z \\
          {shlex.quote(image)}
        """
    )
    return {
        "scripts/sandbox/db-up": up,
        "scripts/sandbox/db-down": "#!/usr/bin/env sh\nset -eu\n"
        + _host_side_guard()
        + f"\npodman stop {shlex.quote(name)} || true\n",
        "scripts/sandbox/db-shell": "#!/usr/bin/env sh\nset -eu\n"
        + _host_side_guard()
        + f"\npodman exec -it {shlex.quote(name)} /bin/sh\n",
        "scripts/sandbox/db-logs": "#!/usr/bin/env sh\nset -eu\n"
        + _host_side_guard()
        + f"\npodman logs -f {shlex.quote(name)}\n",
        ".env.sandbox.example": env_sandbox_example(config),
    }


def web_script(config: ProjectConfig) -> dict[str, str]:
    if config.project_type not in {"web", "api"}:
        return {}
    return {
        "scripts/sandbox/web": _script_prelude(config)
        + clean(
            """

            if inside_agentkit_sandbox; then
              exec sh -lc './scripts/run.sh --host 127.0.0.1 || ./scripts/run.sh'
            fi

            run_project_container sh -lc './scripts/run.sh --host 127.0.0.1 || ./scripts/run.sh'
            """
        )
    }


def game_scripts(config: ProjectConfig) -> dict[str, str]:
    if config.project_type != "game" and "godot" not in config.languages:
        return {}
    return {
        "scripts/sandbox/headless-test": _script_prelude(config)
        + clean(
            """

            if inside_agentkit_sandbox; then
              printf '%s\\n' 'Already inside the Agent Kit sandbox. Running ./scripts/check.sh directly.'
              exec ./scripts/check.sh
            fi

            run_project_container ./scripts/check.sh
            """
        ),
        "scripts/playtest-host": "#!/usr/bin/env sh\nset -eu\nprintf '%s\\n' 'Run interactive GPU/audio/controller playtesting on the host with the project runtime.'\n./scripts/run.sh\n",
    }


def sandbox_readme(config: ProjectConfig) -> str:
    return clean(
        """
        # Agent Kit rootless Podman sandbox

        This sandbox uses rootless Podman with the project mounted at `/workspace`.
        It reduces host filesystem risk, but it is not a magic safety boundary: untrusted code can still damage mounted project files and misuse network access when networking is enabled.

        Run `scripts/sandbox/*` wrappers from the host project root. Once you are already inside the container,
        run project commands directly, such as `./scripts/check.sh`, instead of launching Podman again.

        The sandbox does not mount host `~/.codex`, `~/.ssh`, browser profiles, GPG/SSH agents, GitHub credentials, production configs, or the host home directory by default.
        """
    )


def sandbox_doc(config: ProjectConfig) -> str:
    game_note = (
        "\nInteractive GPU/audio/controller playtesting is usually better on the host. The sandbox is for headless checks and export/test flows; GUI passthrough can be considered later as an explicit advanced profile.\n"
        if config.project_type == "game" or "godot" in config.languages
        else ""
    )
    mode_note = (
        "\nIn `toolchain` mode, Codex normally runs on the host and edits the project directory directly. The container boundary applies to build, test, database, and toolchain commands run through `scripts/sandbox/*`. Source files still live in the local project and are mounted into the container at `/workspace`.\n"
        if config.sandbox.mode == "toolchain"
        else "\nIn Codex-inside-container mode, use the generated `codex-login`, `codex`, and `resume` scripts only after explicit user action. Do not mount or copy host Codex auth into the container.\n"
        if config.sandbox.codex_inside_container
        else "\nIn files-only mode, these files are generated for review and are not the default execution path until a human explicitly chooses to use them.\n"
    )
    return clean(
        f"""
        # Sandbox

        This project can use a rootless Podman sandbox. Mode: `{config.sandbox.mode}`.
        {mode_note}

        ## Safety model

        - Codex's own sandbox is still separate from the container.
        - Rootless Podman reduces host filesystem risk but does not make untrusted code magically safe.
        - The project is mounted at `/workspace`; container commands can still modify mounted project files.
        - Do not mount production secrets, host `~/.codex`, SSH keys, browser profiles, or the host home directory.
        - Do not use `--dangerously-bypass-approvals-and-sandbox`.
        - Do not use host `danger-full-access` as the default answer to permission problems.

        ## Commands

        Host-side sandbox wrappers:

        ```bash
        scripts/sandbox/doctor
        scripts/sandbox/build
        scripts/sandbox/check
        scripts/sandbox/shell
        ```

        Inside-container project commands:

        ```bash
        ./scripts/check.sh
        # or focused project commands such as npm test, python3 -m unittest, cargo test, or go test ./...
        ```

        Do not run host-side sandbox launchers from inside the container. The generated `check`, `exec`, `shell`,
        `web`, and `headless-test` helpers detect container execution and run project commands directly. Host-only
        helpers such as `build`, `codex`, `codex-login`, `resume`, `codex-exec`, and database service wrappers
        refuse to run inside the container instead of attempting nested Podman.

        Human host preflight:

        ```bash
        agent-starter sandbox preflight .
        scripts/sandbox/doctor
        scripts/sandbox/build
        ```

        Run host-side Podman wrappers from a normal host terminal before launching Codex. `agent-starter sandbox
        preflight .` writes `.agent-starter/sandbox/preflight.json` after a successful host preflight. If that
        file exists and reports `"status": "passed"`, an already-open constrained Codex session should not rerun
        `scripts/sandbox/doctor` or `scripts/sandbox/build`.

        Codex may run `scripts/sandbox/check` only when its current sandbox/approval policy permits rootless
        Podman access. If a host-side wrapper fails with a Podman runtime/sandbox error from inside Codex, record
        the exact failure and use `BLOCKED_ENVIRONMENT` until the human runs the preflight/check from a normal
        host terminal or launches Codex inside the container. Do not request `danger-full-access`, host
        full-access, privileged containers, or Podman socket mounts to make these wrappers work.

        If the sandbox was requested for build/test work, do not silently fall back to host build/test commands
        when `doctor`, `build`, or `check` fails. Record the exact failure and either stop with
        `BLOCKED_ENVIRONMENT` or ask the human whether a temporary host-only fallback is acceptable.

        For Codex inside the container:

        ```bash
        scripts/sandbox/codex-login
        scripts/sandbox/codex
        scripts/sandbox/resume
        ```

        `codex-login` uses device authorization inside the project-specific Codex home volume. Do not copy host auth files into the container. Prefer a handoff summary over raw host session import.
        {game_note}
        """
    )


def autonomous_prompt(config: ProjectConfig) -> str:
    return clean(
        """
        # First-run autonomous sandbox prompt

        Use this only for disposable/local development workspaces. The sandbox is part of the requested execution boundary; do not request host full-access.

        Continue until exactly one terminal state is reached:

        - COMPLETE
        - BLOCKED_PERMISSION
        - BLOCKED_DECISION
        - BLOCKED_ENVIRONMENT
        - BLOCKED_FAILURE
        - PLAN_READY

        Work rules:

        - Do not ask for Codex `danger-full-access`, host full-access, privileged containers, or Podman socket mounts to make Podman work.
        - Host-side sandbox preflight should be run before Codex launch through `agent-starter sandbox preflight .`, which writes `.agent-starter/sandbox/preflight.json` after success.
        - If `.agent-starter/sandbox/preflight.json` exists and reports `"status": "passed"`, do not rerun `scripts/sandbox/doctor` or `scripts/sandbox/build` from inside this Codex session.
        - Use `scripts/sandbox/check` only when the current Codex sandbox/approval policy permits rootless Podman access.
        - If host-side sandbox verification is required but unavailable from this Codex session, stop with `BLOCKED_ENVIRONMENT` and tell the human to run `agent-starter sandbox preflight .` or `scripts/sandbox/check` from a normal host terminal, or launch Codex inside the container.
        - If this Codex session is already inside the container, run `./scripts/check.sh` and focused project commands directly; do not run host-side `scripts/sandbox/*` launchers from inside the container.
        - Do not silently fall back to host build/test commands if `scripts/sandbox/doctor`, `scripts/sandbox/build`, or `scripts/sandbox/check` fails.
        - If the sandbox is unavailable, record the exact failure and stop with `BLOCKED_ENVIRONMENT` unless the human explicitly approves a host-only fallback.
        - Do not install host packages.
        - Do not deploy.
        - Do not rsync to production.
        - Do not create GitHub remotes or push without approval.
        - Do not mount real secrets.
        - Do not bypass Codex sandboxing.
        - Update `docs/11-IMPLEMENTATION-NOTES.md` before stopping.
        """
    )


def handoff_prompt(config: ProjectConfig) -> str:
    del config
    return clean(
        """
        # Create a Codex container handoff

        Write `docs/CODEX-HANDOFF.md` for a future Codex session that may run inside the project sandbox.

        Include:

        - current objective;
        - decisions made;
        - files changed;
        - tests and commands run with results;
        - known failures or blockers;
        - next step.
        - whether the next session is expected to run on the host or already inside the container.

        Rules:

        - Do not include OAuth tokens, API keys, cookies, passwords, device codes, SSH keys, browser profile paths, or credential file contents.
        - Do not copy raw Codex session transcripts.
        - Do not tell an inside-container session to run host-side `scripts/sandbox/*` launchers; use direct project commands such as `./scripts/check.sh`.
        - Do not reference host-only paths unless needed to explain a migration issue.
        - Prefer paths relative to the project root.
        - Keep the handoff concise enough for a new session to read before continuing.
        """
    )


def file_map(config: ProjectConfig) -> dict[str, str]:
    if not config.sandbox.enabled:
        return {}
    files = {
        ".agent-starter/sandbox/Containerfile": containerfile(config),
        ".agent-starter/sandbox/sandbox.json": sandbox_json(config),
        ".agent-starter/sandbox/README.md": sandbox_readme(config),
        "docs/12-SANDBOX.md": sandbox_doc(config),
        "scripts/sandbox/doctor": doctor_script(config),
        "scripts/sandbox/build": build_script(config),
        "scripts/sandbox/shell": shell_script(config),
        "scripts/sandbox/exec": exec_script(config),
        "scripts/sandbox/check": check_script(config),
        "scripts/sandbox/logs": logs_script(config),
        "scripts/sandbox/clean": clean_script(config),
        "docs/agent-prompts/create-container-handoff.md": handoff_prompt(config),
    }
    if config.sandbox.codex_inside_container:
        files.update(
            {
                "scripts/sandbox/codex": codex_script(config),
                "scripts/sandbox/codex-login": codex_login_script(config),
                "scripts/sandbox/resume": resume_script(config),
                "scripts/sandbox/codex-exec": codex_exec_script(config),
            }
        )
    files.update(db_scripts(config))
    files.update(web_script(config))
    files.update(game_scripts(config))
    if config.sandbox.first_run_autonomous_prompt:
        files["FIRST_RUN_AUTONOMOUS.md"] = autonomous_prompt(config)
    return files


def doctor_lines(root: Path) -> tuple[int, list[str]]:
    """Return sandbox doctor diagnostics without mutating the host."""
    root = root.expanduser().resolve()
    lines = [f"Agent Kit sandbox doctor: {root}"]
    code = 0
    config_path = root / ".agent-starter" / "sandbox" / "sandbox.json"
    if config_path.is_file():
        lines.append("[ok] sandbox config exists")
        try:
            config = json.loads(config_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            lines.append(f"[fail] sandbox config is invalid JSON: {exc}")
            return 2, lines
        if config.get("engine") == "podman":
            lines.append("[ok] sandbox engine: podman")
        else:
            lines.append(f"[fail] unsupported sandbox engine: {config.get('engine', 'missing')}")
            code = 2
        image = str(config.get("image") or "")
    else:
        lines.append("[fail] missing .agent-starter/sandbox/sandbox.json")
        lines.append("Generate a project with sandbox.enabled true before using sandbox commands.")
        return 2, lines

    podman = shutil.which("podman")
    if podman is None:
        lines.append("[missing] podman")
        lines.append(f"Review on CachyOS: {CACHYOS_PODMAN_COMMAND}")
        return 2, lines
    lines.append(f"[ok] podman: {podman}")

    try:
        info = subprocess.run(
            ["podman", "info", "--format", "{{.Host.Security.Rootless}}"],
            cwd=root,
            text=True,
            capture_output=True,
            check=False,
            timeout=20,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        lines.append(f"[fail] podman info did not complete: {exc}")
        return 2, lines
    if info.returncode != 0:
        detail = (info.stderr or info.stdout).strip()
        lines.append(f"[fail] podman info failed: {detail}")
        return 2, lines
    if (info.stdout or "").strip().lower() == "true":
        lines.append("[ok] Podman reports rootless mode")
    else:
        lines.append("[warn] Podman did not report confirmed rootless mode")

    user_name = ""
    try:
        user = subprocess.run(["id", "-un"], text=True, capture_output=True, check=False, timeout=5)
        user_name = (user.stdout or "").strip() if user.returncode == 0 else ""
    except (OSError, subprocess.TimeoutExpired):
        user_name = ""
    for path in (Path("/etc/subuid"), Path("/etc/subgid")):
        if not user_name or not path.is_file():
            lines.append(f"[warn] {path} not inspectable")
            continue
        try:
            has_mapping = any(line.startswith(f"{user_name}:") for line in path.read_text(encoding="utf-8", errors="replace").splitlines())
        except OSError:
            has_mapping = False
        lines.append(f"[{'ok' if has_mapping else 'warn'}] {path} {'has' if has_mapping else 'does not show'} a mapping for this user")

    if shutil.which("pasta") or shutil.which("passt"):
        lines.append("[ok] rootless networking helper found")
    else:
        lines.append("[warn] passt/pasta not found; rootless networking may be limited")
    if shutil.which("fuse-overlayfs"):
        lines.append("[ok] fuse-overlayfs found")
    else:
        lines.append("[warn] fuse-overlayfs not found; Podman may use another storage driver")

    if image:
        image_check = subprocess.run(["podman", "image", "exists", image], cwd=root, check=False, timeout=20)
        if image_check.returncode == 0:
            lines.append(f"[ok] sandbox image exists: {image}")
        else:
            lines.append(f"[info] sandbox image needs build: scripts/sandbox/build ({image})")
    return code, lines
