"""Rootless Podman sandbox file rendering."""

from __future__ import annotations

import json
import shlex
import shutil
import subprocess
from pathlib import Path

from .models import ProjectConfig
from .platforms.arch import arch_packages_for_capabilities
from .platforms.debian import debian_packages_for_capabilities
from .templates import clean
from .toolchains import capabilities_for, unique


SANDBOX_EXECUTABLES: tuple[str, ...] = (
    "scripts/sandbox/doctor",
    "scripts/sandbox/preflight",
    "scripts/sandbox/status",
    "scripts/sandbox/build",
    "scripts/sandbox/shell",
    "scripts/sandbox/exec",
    "scripts/sandbox/check",
    "scripts/sandbox/logs",
    "scripts/sandbox/clean",
    "scripts/sandbox/codex",
    "scripts/sandbox/codex-login",
    "scripts/sandbox/resume",
    "scripts/sandbox/codex-exec",
    "scripts/sandbox/db-up",
    "scripts/sandbox/db-down",
    "scripts/sandbox/db-shell",
    "scripts/sandbox/db-logs",
    "scripts/sandbox/web",
    "scripts/sandbox/headless-test",
    "scripts/sandbox/playtest-gui",
    "scripts/playtest-host",
)

ROOTLESS_PODMAN_ARCH_PACKAGES = arch_packages_for_capabilities(("sandbox.rootless-podman",))
CACHYOS_PODMAN_COMMAND = "sudo pacman -S --needed " + " ".join(ROOTLESS_PODMAN_ARCH_PACKAGES)
SANDBOX_ENV_MARKER = "AGENTKIT_INSIDE_SANDBOX=1"
HOST_SIDE_SANDBOX_MESSAGE = "This is a host-side sandbox command. Exit the container and run it from the project root on the host."


def project_id(config: ProjectConfig) -> str:
    slug = config.project_slug or "project"
    return "".join(character if character.isalnum() else "-" for character in slug.lower()).strip("-") or "project"


def image_name(config: ProjectConfig) -> str:
    return f"agentkit-{project_id(config)}:dev"


def volume_name(config: ProjectConfig, suffix: str) -> str:
    return f"agentkit_{project_id(config)}_{suffix}"


def sandbox_json(config: ProjectConfig) -> str:
    payload = {
        "schema_version": 1,
        "engine": "podman",
        "mode": config.sandbox.mode,
        "image_profile": config.sandbox.image_profile,
        "rootless_required": config.sandbox.rootless_required,
        "codex_inside_container": config.sandbox.codex_inside_container,
        "workspace_mount": "/workspace",
        "user_namespace": "keep-id",
        "runtime_user": "host uid/gid from id -u/id -g",
        "network_default": "none for toolchain check/exec/shell; build and explicit Codex container flows may use network",
        "image": image_name(config),
        "volumes": {
            "codex_home": volume_name(config, "codex_home"),
            "db_data": volume_name(config, "db_data"),
        },
        "project_local_paths": {
            "container_home": ".agent-starter/container-home",
            "cache": ".agent-starter/cache",
            "logs": ".agent-starter/logs",
        },
        "advanced_passthrough": {
            "gpu_audio_controller": config.sandbox.gui_passthrough,
        },
        "mount_policy": {
            "project_workspace": "rw",
            "host_home": "not-mounted",
            "host_codex_home": "not-mounted",
            "host_ssh": "not-mounted",
            "host_browser_profiles": "not-mounted",
            "host_git_credentials": "not-mounted",
        },
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def containerfile(config: ProjectConfig) -> str:
    capability_ids = capabilities_for(config.languages, config.database, github=False)
    if config.sandbox.codex_inside_container:
        capability_ids.append("language.javascript")
    if config.sandbox.image_profile == "debian-toolchain":
        packages = debian_packages_for_capabilities(capability_ids)
        base_image = "docker.io/library/debian:stable-slim"
        profile_note = "Debian toolchain image selected explicitly; this choice is independent of the host distribution."
        install_command = "apt-get update && apt-get install --yes --no-install-recommends {packages} && rm -rf /var/lib/apt/lists/*"
    else:
        packages = arch_packages_for_capabilities(capability_ids)
        base_image = "docker.io/library/archlinux:base-devel"
        profile_note = "Arch toolchain image selected explicitly; this choice is independent of the host distribution."
        install_command = "pacman -Syu --noconfirm --needed {packages} && pacman -Scc --noconfirm"
    install = " ".join(shlex.quote(package) for package in packages)
    codex_note = (
        "\n# Codex CLI is installed only for explicit codex-inside-container mode.\n"
        "RUN npm install -g @openai/codex\n"
        if config.sandbox.codex_inside_container
        else ""
    )
    return clean(
        f"""
        # Generated by CLI AI Agent Starter Kit.
        # {profile_note}
        FROM {base_image}

        RUN {install_command.format(packages=install)}
        RUN mkdir -p /workspace /home/codex /tmp/agentkit-home \\
            && chmod 1777 /tmp/agentkit-home \\
            && chmod 0755 /home/codex
        {codex_note}
        WORKDIR /workspace
        """
    )


def _inside_sandbox_helper() -> str:
    return clean(
        """
        inside_agentkit_sandbox() {
          test "${AGENTKIT_INSIDE_SANDBOX:-}" = "1" && return 0
          test -f /run/.containerenv && return 0
          test -f /.dockerenv && return 0
          return 1
        }
        """
    )


def _host_side_guard() -> str:
    return (
        _inside_sandbox_helper()
        + "\n"
        + clean(
            f"""
            if inside_agentkit_sandbox; then
              printf '%s\\n' {shlex.quote(HOST_SIDE_SANDBOX_MESSAGE)}
              exit 2
            fi
            """
        )
    )


def _script_prelude(config: ProjectConfig) -> str:
    return clean(
        f"""
        #!/usr/bin/env sh
        set -eu
        ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
        IMAGE={shlex.quote(image_name(config))}
        WORKSPACE=/workspace
        CACHE_VOLUME={shlex.quote(volume_name(config, "cache"))}
        CODEX_HOME_VOLUME={shlex.quote(volume_name(config, "codex_home"))}
        DB_VOLUME={shlex.quote(volume_name(config, "db_data"))}
        HOST_UID=$(id -u)
        HOST_GID=$(id -g)
        CONTAINER_HOME=/tmp/agentkit-home
        CONTAINER_CACHE=/tmp/agentkit-cache
        HOST_CONTAINER_HOME="$ROOT/.agent-starter/container-home"
        HOST_CACHE="$ROOT/.agent-starter/cache"
        LOG_DIR="$ROOT/.agent-starter/logs"
        SANDBOX_NETWORK=${{AGENTKIT_SANDBOX_NETWORK:-none}}

        {_inside_sandbox_helper()}

        prepare_project_container_dirs() {{
          mkdir -p "$HOST_CONTAINER_HOME" "$HOST_CACHE" "$LOG_DIR"
        }}

        run_project_container() {{
          prepare_project_container_dirs
          podman run --rm \\
            --label agentkit.project={shlex.quote(project_id(config))} \\
            --label agentkit.generated=true \\
            --userns=keep-id \\
            --user "$HOST_UID:$HOST_GID" \\
            --network "$SANDBOX_NETWORK" \\
            --security-opt=no-new-privileges \\
            --cap-drop=all \\
            --pids-limit "${{AGENTKIT_SANDBOX_PIDS_LIMIT:-512}}" \\
            --env AGENTKIT_INSIDE_SANDBOX=1 \\
            --env HOME="$CONTAINER_HOME" \\
            --env XDG_CACHE_HOME="$CONTAINER_CACHE/xdg-cache" \\
            --env XDG_CONFIG_HOME="$CONTAINER_HOME/.config" \\
            --env NPM_CONFIG_CACHE="$CONTAINER_CACHE/npm" \\
            --env YARN_CACHE_FOLDER="$CONTAINER_CACHE/yarn" \\
            --env PNPM_HOME="$CONTAINER_CACHE/pnpm-home" \\
            --env PIP_CACHE_DIR="$CONTAINER_CACHE/pip" \\
            --env COMPOSER_CACHE_DIR="$CONTAINER_CACHE/composer" \\
            --env CARGO_HOME="$CONTAINER_CACHE/cargo" \\
            --env GOPATH="$CONTAINER_CACHE/go" \\
            --volume "$ROOT:/workspace:Z" \\
            --volume "$HOST_CONTAINER_HOME:$CONTAINER_HOME:Z" \\
            --volume "$HOST_CACHE:$CONTAINER_CACHE:Z" \\
            --workdir /workspace \\
            "$IMAGE" "$@"
        }}
        """
    )


def doctor_script(config: ProjectConfig) -> str:
    return clean(
        f"""
        #!/usr/bin/env sh
        set -eu
        ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
        {_host_side_guard()}
        printf '%s\\n' 'Agent Kit rootless Podman sandbox doctor'
        if ! command -v podman >/dev/null 2>&1; then
          printf '%s\\n' '[missing] podman'
          printf 'Review on CachyOS: %s\\n' {shlex.quote(CACHYOS_PODMAN_COMMAND)}
          exit 2
        fi
        podman info >/dev/null
        if podman info --format '{{{{.Host.Security.Rootless}}}}' 2>/dev/null | grep -qi true; then
          printf '%s\\n' '[ok] Podman reports rootless mode.'
        else
          printf '%s\\n' '[warn] Could not confirm rootless mode from podman info.'
        fi
        USER_NAME=$(id -un)
        printf '[ok] host user id: %s:%s\\n' "$(id -u)" "$(id -g)"
        grep -q "^${{USER_NAME}}:" /etc/subuid 2>/dev/null && printf '%s\\n' '[ok] /etc/subuid has a mapping for this user.' || printf '%s\\n' '[warn] /etc/subuid mapping not found or not inspectable.'
        grep -q "^${{USER_NAME}}:" /etc/subgid 2>/dev/null && printf '%s\\n' '[ok] /etc/subgid has a mapping for this user.' || printf '%s\\n' '[warn] /etc/subgid mapping not found or not inspectable.'
        if podman run --help 2>/dev/null | grep -q -- '--userns'; then
          printf '%s\\n' '[ok] Podman supports --userns=keep-id for host-owned workspace files.'
        else
          printf '%s\\n' '[warn] Could not confirm Podman --userns support; workspace file ownership may need review.'
        fi
        command -v pasta >/dev/null 2>&1 || command -v passt >/dev/null 2>&1 || printf '%s\\n' '[warn] passt/pasta not found; rootless networking may be limited.'
        command -v fuse-overlayfs >/dev/null 2>&1 || printf '%s\\n' '[warn] fuse-overlayfs not found; Podman may use another storage driver.'
        test -f "$ROOT/.agent-starter/sandbox/sandbox.json" && printf '%s\\n' '[ok] sandbox config exists.'
        podman image exists {shlex.quote(image_name(config))} && printf '%s\\n' '[ok] sandbox image exists.' || printf '%s\\n' '[info] sandbox image needs build: scripts/sandbox/build'
        """
    )


def build_script(config: ProjectConfig) -> str:
    return clean(
        f"""
        #!/usr/bin/env sh
        set -eu
        ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
        {_host_side_guard()}
        if podman image exists {shlex.quote(image_name(config))} && [ "${{1:-}}" != "--rebuild" ]; then
          printf '%s\\n' 'Sandbox image already exists; reusing it. Run scripts/sandbox/build --rebuild to rebuild.'
          exit 0
        fi
        podman build \\
          --label agentkit.project={shlex.quote(project_id(config))} \\
          --label agentkit.generated=true \\
          -t {shlex.quote(image_name(config))} \\
          -f "$ROOT/.agent-starter/sandbox/Containerfile" \\
          "$ROOT"
        """
    )


def preflight_script(config: ProjectConfig) -> str:
    inputs = (
        ".agent-starter/project.json",
        ".agent-starter/sandbox/Containerfile",
        ".agent-starter/sandbox/sandbox.json",
        "scripts/sandbox/doctor",
        "scripts/sandbox/preflight",
        "scripts/sandbox/build",
        "scripts/sandbox/check",
    )
    input_args = " ".join(shlex.quote(item) for item in inputs)
    input_json_lines = "\n".join(
        f"            printf '    \"{item}\": \"%s\"{',' if index < len(inputs) - 1 else ''}\\n' \"$(hash_file {shlex.quote(item)})\""
        for index, item in enumerate(inputs)
    )
    return clean(
        f"""
        #!/usr/bin/env sh
        set -eu
        ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
        cd "$ROOT"
        {_host_side_guard()}

        find_agent_starter() {{
          if command -v agent-starter >/dev/null 2>&1; then
            command -v agent-starter
            return 0
          fi
          if [ -x "$ROOT/../agent-starter" ]; then
            printf '%s\\n' "$ROOT/../agent-starter"
            return 0
          fi
          return 1
        }}

        if AGENT_STARTER=$(find_agent_starter); then
          exec "$AGENT_STARTER" sandbox preflight "$ROOT" "$@"
        fi

        LOG_DIR="$ROOT/.agent-starter/logs"
        SANDBOX_DIR="$ROOT/.agent-starter/sandbox"
        STAMP="$SANDBOX_DIR/preflight.json"
        IMAGE={shlex.quote(image_name(config))}
        mkdir -p "$LOG_DIR" "$SANDBOX_DIR"
        RUN_CHECK=true
        if [ "${{1:-}}" = "--no-check" ]; then
          RUN_CHECK=false
        fi

        hash_file() {{
          if [ -f "$1" ]; then
            sha256sum "$1" | awk '{{print $1}}'
          else
            printf '%s' missing
          fi
        }}

        sandbox_fingerprint() {{
          for relative in {input_args}
          do
            printf '%s  %s\\n' "$(hash_file "$relative")" "$relative"
          done | sha256sum | awk '{{print $1}}'
        }}

        write_stamp() {{
          status=$1
          failed_step=${{2:-}}
          image_id=$(podman image inspect --format '{{{{.Id}}}}' "$IMAGE" 2>/dev/null || true)
          fingerprint=$(sandbox_fingerprint)
          tmp="$STAMP.tmp.$$"
          {{
            printf '%s\\n' '{{'
            printf '  "schema_version": 1,\\n'
            printf '  "created_at": "%s",\\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
            printf '  "status": "%s",\\n' "$status"
            printf '  "failed_step": "%s",\\n' "$failed_step"
            printf '  "mode": "%s",\\n' {shlex.quote(config.sandbox.mode)}
            printf '  "engine": "podman",\\n'
            printf '  "image": "%s",\\n' "$IMAGE"
            printf '  "image_id": "%s",\\n' "$image_id"
            printf '  "run_check": %s,\\n' "$RUN_CHECK"
            printf '  "sandbox_fingerprint": "%s",\\n' "$fingerprint"
            printf '  "inputs": {{\\n'
        {input_json_lines}
            printf '\\n  }},\\n'
            printf '  "note": "Generated fallback preflight completed on the host. This file contains no credentials."\\n'
            printf '%s\\n' '}}'
          }} > "$tmp"
          mv "$tmp" "$STAMP"
        }}

        run_logged() {{
          label=$1
          script=$2
          log=$3
          printf '== %s ==\\n' "$label"
          if "$script" >"$log" 2>&1; then
            cat "$log"
            return 0
          fi
          code=$?
          cat "$log"
          write_stamp failed "$label"
          printf '[fail] %s exited with %s. See %s\\n' "$label" "$code" "$log" >&2
          exit "$code"
        }}

        run_logged "sandbox doctor" "$ROOT/scripts/sandbox/doctor" "$LOG_DIR/sandbox-preflight-doctor.log"
        run_logged "sandbox build" "$ROOT/scripts/sandbox/build" "$LOG_DIR/sandbox-build.log"
        if [ "$RUN_CHECK" = true ]; then
          run_logged "sandbox check" "$ROOT/scripts/sandbox/check" "$LOG_DIR/sandbox-check.log"
        fi
        write_stamp passed ""
        printf 'Sandbox preflight passed. Wrote %s\\n' "$STAMP"
        """
    )


def status_script(config: ProjectConfig) -> str:
    inputs = (
        ".agent-starter/project.json",
        ".agent-starter/sandbox/Containerfile",
        ".agent-starter/sandbox/sandbox.json",
        "scripts/sandbox/doctor",
        "scripts/sandbox/preflight",
        "scripts/sandbox/build",
        "scripts/sandbox/check",
    )
    input_args = " ".join(shlex.quote(item) for item in inputs)
    return clean(
        f"""
        #!/usr/bin/env sh
        set -eu
        ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
        cd "$ROOT"

        inside_agentkit_sandbox() {{
          test "${{AGENTKIT_INSIDE_SANDBOX:-}}" = "1" && return 0
          test -f /run/.containerenv && return 0
          test -f /.dockerenv && return 0
          return 1
        }}

        find_agent_starter() {{
          if command -v agent-starter >/dev/null 2>&1; then
            command -v agent-starter
            return 0
          fi
          if ! inside_agentkit_sandbox && [ -x "$ROOT/../agent-starter" ]; then
            printf '%s\\n' "$ROOT/../agent-starter"
            return 0
          fi
          return 1
        }}

        if AGENT_STARTER=$(find_agent_starter); then
          exec "$AGENT_STARTER" status "$ROOT"
        fi

        STAMP="$ROOT/.agent-starter/sandbox/preflight.json"
        IMAGE={shlex.quote(image_name(config))}

        hash_file() {{
          if [ -f "$1" ]; then
            sha256sum "$1" | awk '{{print $1}}'
          else
            printf '%s' missing
          fi
        }}

        sandbox_fingerprint() {{
          for relative in {input_args}
          do
            printf '%s  %s\\n' "$(hash_file "$relative")" "$relative"
          done | sha256sum | awk '{{print $1}}'
        }}

        json_string() {{
          key=$1
          sed -n 's/^[[:space:]]*"'$key'"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/p' "$STAMP" | head -n 1
        }}

        printf 'Sandbox mode: %s\\n' {shlex.quote(config.sandbox.mode)}
        printf 'Sandbox engine: podman\\n'
        printf 'Sandbox image: %s\\n' "$IMAGE"
        if [ ! -f "$STAMP" ]; then
          printf 'Sandbox preflight: missing\\n'
          printf 'Reason: .agent-starter/sandbox/preflight.json is missing. Run scripts/sandbox/preflight from a normal host terminal.\\n'
          exit 0
        fi

        status=$(json_string status)
        created=$(json_string created_at)
        recorded=$(json_string sandbox_fingerprint)
        current=$(sandbox_fingerprint)
        printf 'Last preflight: %s\\n' "${{created:-unknown}}"
        if [ "$status" != passed ]; then
          failed=$(json_string failed_step)
          printf 'Sandbox preflight: failed\\n'
          printf 'Reason: %s\\n' "${{failed:-last preflight did not pass}}"
          exit 0
        fi
        if [ "$recorded" != "$current" ]; then
          printf 'Sandbox preflight: stale\\n'
          printf 'Reason: generated sandbox files changed after last preflight. Run scripts/sandbox/preflight from a normal host terminal.\\n'
          exit 0
        fi
        printf 'Sandbox preflight: valid\\n'
        printf 'Reason: preflight stamp is current. Do not rerun scripts/sandbox/doctor or scripts/sandbox/build from a constrained Codex session.\\n'
        """
    )


def shell_script(config: ProjectConfig) -> str:
    return _script_prelude(config) + clean(
        """

        if inside_agentkit_sandbox; then
          exec /bin/sh
        fi

        run_interactive_project_container() {
          prepare_project_container_dirs
          podman run --rm -it \\
            --label agentkit.project=__PROJECT_ID__ \\
            --label agentkit.generated=true \\
            --userns=keep-id \\
            --user "$HOST_UID:$HOST_GID" \\
            --network "$SANDBOX_NETWORK" \\
            --security-opt=no-new-privileges \\
            --cap-drop=all \\
            --pids-limit "${AGENTKIT_SANDBOX_PIDS_LIMIT:-512}" \\
            --env AGENTKIT_INSIDE_SANDBOX=1 \\
            --env HOME="$CONTAINER_HOME" \\
            --env XDG_CACHE_HOME="$CONTAINER_CACHE/xdg-cache" \\
            --env XDG_CONFIG_HOME="$CONTAINER_HOME/.config" \\
            --env NPM_CONFIG_CACHE="$CONTAINER_CACHE/npm" \\
            --env YARN_CACHE_FOLDER="$CONTAINER_CACHE/yarn" \\
            --env PNPM_HOME="$CONTAINER_CACHE/pnpm-home" \\
            --env PIP_CACHE_DIR="$CONTAINER_CACHE/pip" \\
            --env COMPOSER_CACHE_DIR="$CONTAINER_CACHE/composer" \\
            --env CARGO_HOME="$CONTAINER_CACHE/cargo" \\
            --env GOPATH="$CONTAINER_CACHE/go" \\
            --volume "$ROOT:/workspace:Z" \\
            --volume "$HOST_CONTAINER_HOME:$CONTAINER_HOME:Z" \\
            --volume "$HOST_CACHE:$CONTAINER_CACHE:Z" \\
            --workdir /workspace \\
            "$IMAGE" "$@"
        }

        run_interactive_project_container /bin/sh
        """
    ).replace("__PROJECT_ID__", shlex.quote(project_id(config)))


def exec_script(config: ProjectConfig) -> str:
    return _script_prelude(config) + clean(
        """

        if inside_agentkit_sandbox; then
          if [ "$#" -eq 0 ]; then
            printf '%s\\n' 'Already inside the Agent Kit sandbox. No command was provided.'
            exit 2
          fi
          exec "$@"
        fi

        run_project_container "$@"
        """
    )


def check_script(config: ProjectConfig) -> str:
    return _script_prelude(config) + clean(
        """

        if inside_agentkit_sandbox; then
          printf '%s\\n' 'Already inside the Agent Kit sandbox. Running ./scripts/check.sh directly.'
          exec ./scripts/check.sh
        fi

        run_project_container ./scripts/check.sh
        """
    )


def logs_script(config: ProjectConfig) -> str:
    return clean(
        f"""
        #!/usr/bin/env sh
        set -eu
        {_host_side_guard()}
        podman ps -a --filter name={shlex.quote('agentkit-' + project_id(config))}
        """
    )


def clean_script(config: ProjectConfig) -> str:
    return clean(
        f"""
        #!/usr/bin/env sh
        set -eu
        {_host_side_guard()}
        printf '%s\\n' 'This removes stopped sandbox containers only. Volumes are preserved.'
        REMOVE_IMAGE=0
        REMOVE_VOLUMES=0
        DRY_RUN=0
        FORCE=0
        YES=0
        for arg in "$@"; do
          case "$arg" in
            --image) REMOVE_IMAGE=1 ;;
            --volumes) REMOVE_VOLUMES=1 ;;
            --all) REMOVE_IMAGE=1; REMOVE_VOLUMES=1 ;;
            --dry-run) DRY_RUN=1 ;;
            --force) FORCE=1; YES=1 ;;
            --yes) YES=1; FORCE=1 ;;
            *)
              printf 'Unknown option: %s\\n' "$arg"
              printf '%s\\n' 'Usage: scripts/sandbox/clean [--dry-run] [--image] [--volumes] [--all] [--force|--yes]'
              exit 2
              ;;
          esac
        done
        containers=$(podman ps -aq --filter label=agentkit.project={shlex.quote(project_id(config))} --filter label=agentkit.generated=true || true)
        if [ "$DRY_RUN" -eq 1 ]; then
          printf '%s\\n' 'Dry run: would remove matching generated sandbox resources only.'
          printf 'Containers with labels agentkit.project=%s, agentkit.generated=true:\\n' {shlex.quote(project_id(config))}
          if [ -n "$containers" ]; then printf '%s\\n' "$containers"; else printf '%s\\n' '  none'; fi
          if [ "$REMOVE_IMAGE" -eq 1 ]; then printf 'Image: %s\\n' {shlex.quote(image_name(config))}; fi
          if [ "$REMOVE_VOLUMES" -eq 1 ]; then printf 'Volumes: %s %s\\n' {shlex.quote(volume_name(config, "codex_home"))} {shlex.quote(volume_name(config, "db_data"))}; fi
          exit 0
        fi
        if [ "$FORCE" -ne 1 ]; then
          printf '%s\\n' 'No resources removed. Re-run with --dry-run to inspect or --force to remove matching generated resources.'
          exit 0
        fi
        if [ -n "$containers" ]; then
          printf '%s\\n' "$containers" | xargs podman rm -f
        else
          printf '%s\\n' 'No labeled project containers found.'
        fi
        if [ "$REMOVE_IMAGE" -eq 1 ]; then
          if podman image exists {shlex.quote(image_name(config))}; then
            podman image rm {shlex.quote(image_name(config))}
          else
            printf 'Image not found: %s\\n' {shlex.quote(image_name(config))}
          fi
        fi
        if [ "$REMOVE_VOLUMES" -eq 1 ]; then
          if [ "$YES" -ne 1 ]; then
            printf '%s\\n' 'Refusing to remove project volumes without --force or --yes.'
            printf '%s\\n' 'Volumes can contain Codex container auth/session state, caches, and dev database data.'
            exit 2
          fi
          for volume in {shlex.quote(volume_name(config, "codex_home"))} {shlex.quote(volume_name(config, "db_data"))}
          do
            if podman volume exists "$volume"; then
              podman volume rm "$volume"
            else
              printf 'Volume not found: %s\\n' "$volume"
            fi
          done
        else
          printf '%s\\n' 'Volumes preserved. Add --volumes --force to remove Codex home and database volumes.'
        fi
        """
    )


def codex_script(config: ProjectConfig) -> str:
    base = _script_prelude(config)
    run = (
        'if inside_agentkit_sandbox; then\n'
        "  printf '%s\\n' "
        + shlex.quote(HOST_SIDE_SANDBOX_MESSAGE)
        + "\n"
        "  exit 2\n"
        "fi\n"
        'podman run --rm -it --name agentkit-'
        + project_id(config)
        + '-codex --label agentkit.project='
        + project_id(config)
        + ' --label agentkit.generated=true --userns=keep-id --user "$HOST_UID:$HOST_GID" --env AGENTKIT_INSIDE_SANDBOX=1 --env HOME=/home/codex --volume "$ROOT:/workspace:Z" --volume "$CODEX_HOME_VOLUME:/home/codex:Z,U" '
        '--workdir /workspace '
        + shlex.quote(image_name(config))
        + ' codex --sandbox workspace-write --ask-for-approval on-request\n'
    )
    return base + "\n" + run


def codex_login_script(config: ProjectConfig) -> str:
    return (
        _script_prelude(config)
        + "\n"
        + _host_side_guard()
        + '\npodman run --rm -it --label agentkit.project='
        + project_id(config)
        + ' --label agentkit.generated=true --userns=keep-id --user "$HOST_UID:$HOST_GID" --env AGENTKIT_INSIDE_SANDBOX=1 --env HOME=/home/codex --volume "$ROOT:/workspace:Z" --volume "$CODEX_HOME_VOLUME:/home/codex:Z,U" --workdir /workspace '
        + shlex.quote(image_name(config))
        + " codex login --device-auth\n"
    )


def resume_script(config: ProjectConfig) -> str:
    return (
        _script_prelude(config)
        + "\n"
        + _host_side_guard()
        + '\npodman run --rm -it --label agentkit.project='
        + project_id(config)
        + ' --label agentkit.generated=true --userns=keep-id --user "$HOST_UID:$HOST_GID" --env AGENTKIT_INSIDE_SANDBOX=1 --env HOME=/home/codex --volume "$ROOT:/workspace:Z" --volume "$CODEX_HOME_VOLUME:/home/codex:Z,U" --workdir /workspace '
        + shlex.quote(image_name(config))
        + " codex resume --last\n"
    )


def codex_exec_script(config: ProjectConfig) -> str:
    return _script_prelude(config) + "\n" + _host_side_guard() + clean(
        f"""

        PROMPT_FILE=${{1:-FIRST_RUN_AUTONOMOUS.md}}
        test -f "$ROOT/$PROMPT_FILE"
        podman run --rm -i \\
          --label agentkit.project={shlex.quote(project_id(config))} \\
          --label agentkit.generated=true \\
          --userns=keep-id \\
          --user "$HOST_UID:$HOST_GID" \\
          --env AGENTKIT_INSIDE_SANDBOX=1 \\
          --env HOME=/home/codex \\
          --volume "$ROOT:/workspace:Z" \\
          --volume "$CODEX_HOME_VOLUME:/home/codex:Z,U" \\
          --workdir /workspace \\
          {shlex.quote(image_name(config))} \\
          codex exec --sandbox workspace-write --ask-for-approval never --cd /workspace - < "$ROOT/$PROMPT_FILE"
        """
    )


def env_sandbox_example(config: ProjectConfig) -> str:
    if config.database == "mariadb":
        return "SANDBOX_DB_NAME=app_dev\nSANDBOX_DB_USER=app_dev\nSANDBOX_DB_PASSWORD=dev_password_change_me\nSANDBOX_DB_PORT=3306\n"
    if config.database == "postgresql":
        return "SANDBOX_DB_NAME=app_dev\nSANDBOX_DB_USER=app_dev\nSANDBOX_DB_PASSWORD=dev_password_change_me\nSANDBOX_DB_PORT=5432\n"
    return ""


def db_scripts(config: ProjectConfig) -> dict[str, str]:
    if config.database not in {"mariadb", "postgresql"}:
        return {}
    is_mariadb = config.database == "mariadb"
    image = "docker.io/library/mariadb:latest" if is_mariadb else "docker.io/library/postgres:latest"
    name = f"agentkit-{project_id(config)}-{config.database}"
    volume = volume_name(config, "db_data")
    env_file = "--env-file .env.sandbox"
    port = "3306" if is_mariadb else "5432"
    data_path = "/var/lib/mysql" if is_mariadb else "/var/lib/postgresql/data"
    env_block = (
        "-e MARIADB_DATABASE=${SANDBOX_DB_NAME:-app_dev} \\\n"
        "  -e MARIADB_USER=${SANDBOX_DB_USER:-app_dev} \\\n"
        "  -e MARIADB_PASSWORD=${SANDBOX_DB_PASSWORD:-dev_password_change_me} \\\n"
        "  -e MARIADB_ROOT_PASSWORD=${SANDBOX_DB_PASSWORD:-dev_password_change_me}"
        if is_mariadb
        else "-e POSTGRES_DB=${SANDBOX_DB_NAME:-app_dev} \\\n"
        "  -e POSTGRES_USER=${SANDBOX_DB_USER:-app_dev} \\\n"
        "  -e POSTGRES_PASSWORD=${SANDBOX_DB_PASSWORD:-dev_password_change_me}"
    )
    up = clean(
        f"""
        #!/usr/bin/env sh
        set -eu
        {_host_side_guard()}
        test -f .env.sandbox || cp .env.sandbox.example .env.sandbox
        podman volume exists {shlex.quote(volume)} || podman volume create {shlex.quote(volume)}
        . ./.env.sandbox
        podman run -d --replace --name {shlex.quote(name)} --label agentkit.project={shlex.quote(project_id(config))} --label agentkit.generated=true {env_file} \\
          {env_block} \\
          -p 127.0.0.1:${{SANDBOX_DB_PORT:-{port}}}:{port} \\
          --volume {shlex.quote(volume)}:{data_path}:Z \\
          {shlex.quote(image)}
        """
    )
    return {
        "scripts/sandbox/db-up": up,
        "scripts/sandbox/db-down": "#!/usr/bin/env sh\nset -eu\n"
        + _host_side_guard()
        + f"\npodman stop {shlex.quote(name)} || true\n",
        "scripts/sandbox/db-shell": "#!/usr/bin/env sh\nset -eu\n"
        + _host_side_guard()
        + f"\npodman exec -it {shlex.quote(name)} /bin/sh\n",
        "scripts/sandbox/db-logs": "#!/usr/bin/env sh\nset -eu\n"
        + _host_side_guard()
        + f"\npodman logs -f {shlex.quote(name)}\n",
        ".env.sandbox.example": env_sandbox_example(config),
    }


def web_script(config: ProjectConfig) -> dict[str, str]:
    if config.project_type not in {"web", "api"}:
        return {}
    return {
        "scripts/sandbox/web": _script_prelude(config)
        + clean(
            """

            if inside_agentkit_sandbox; then
              exec sh -lc './scripts/run.sh --host 127.0.0.1 || ./scripts/run.sh'
            fi

            run_project_container sh -lc './scripts/run.sh --host 127.0.0.1 || ./scripts/run.sh'
            """
        )
    }


def game_scripts(config: ProjectConfig) -> dict[str, str]:
    if config.project_type != "game" and "godot" not in config.languages:
        return {}
    files = {
        "scripts/sandbox/headless-test": _script_prelude(config)
        + clean(
            """

            if inside_agentkit_sandbox; then
              mkdir -p artifacts/headless .agent-starter/logs
              if [ -x ./scripts/godot-headless-test.sh ]; then
                printf '%s\\n' 'Already inside the Agent Kit sandbox. Running project Godot headless test hook.'
                exec ./scripts/godot-headless-test.sh
              fi
              printf '%s\\n' 'Already inside the Agent Kit sandbox. No scripts/godot-headless-test.sh hook exists; running ./scripts/check.sh.'
              printf '%s\\n' 'Add scripts/godot-headless-test.sh when the project has a real scene/export/screenshot test.'
              exec ./scripts/check.sh
            fi

            run_project_container sh -lc 'mkdir -p artifacts/headless .agent-starter/logs; if [ -x ./scripts/godot-headless-test.sh ]; then ./scripts/godot-headless-test.sh; else printf "%s\\n" "No scripts/godot-headless-test.sh hook exists; running ./scripts/check.sh."; printf "%s\\n" "Add scripts/godot-headless-test.sh when the project has a real scene/export/screenshot test."; ./scripts/check.sh; fi'
            """
        ),
        "scripts/playtest-host": "#!/usr/bin/env sh\nset -eu\nprintf '%s\\n' 'Run interactive GPU/audio/controller playtesting on the host with the project runtime.'\n./scripts/run.sh\n",
    }
    if "godot" in config.languages:
        files["docs/GODOT-SANDBOX.md"] = godot_sandbox_doc(config)
    if config.sandbox.gui_passthrough:
        files["scripts/sandbox/playtest-gui"] = playtest_gui_script(config)
    return files


def godot_sandbox_doc(config: ProjectConfig) -> str:
    del config
    return clean(
        """
        # Godot sandbox testing

        The default autonomous path for Godot work is headless verification inside the project sandbox:

        ```bash
        scripts/sandbox/headless-test
        ```

        From inside the container, run direct project commands instead of host-side sandbox launchers:

        ```bash
        ./scripts/check.sh
        ./scripts/godot-headless-test.sh
        ```

        `scripts/sandbox/headless-test` creates `artifacts/headless/` and then:

        - runs `scripts/godot-headless-test.sh` if the project adds that executable hook;
        - otherwise falls back to `./scripts/check.sh` and prints that a real Godot hook is still needed.

        Add `scripts/godot-headless-test.sh` after the project has an actual Godot project, scene, export preset,
        or test runner. That hook is the right place for commands such as:

        ```bash
        godot --headless --path . --quit
        godot --headless --path . --export-release "Linux/X11" artifacts/headless/game.x86_64
        ```

        Screenshot or visual smoke tests are project-specific. A future hook may launch a deterministic test scene,
        save screenshots or logs under `artifacts/headless/`, and exit nonzero on failures. Do not promise visual
        coverage until that hook exists and has been verified.

        Interactive rendering, audio, and controller checks usually belong on the host with:

        ```bash
        scripts/playtest-host
        ```

        The optional `scripts/sandbox/playtest-gui` helper is generated only when `sandbox.gui_passthrough` is
        explicitly enabled. It exposes selected host Wayland, GPU, PipeWire audio, and input/controller interfaces
        to the project container, so keep it off unless the user accepts that extra local exposure.
        """
    )


def playtest_gui_script(config: ProjectConfig) -> str:
    return clean(
        f"""
        #!/usr/bin/env sh
        set -eu
        ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
        IMAGE={shlex.quote(image_name(config))}
        {_host_side_guard()}

        USER_ID=$(id -u)
        RUNTIME_DIR=${{XDG_RUNTIME_DIR:-/run/user/$USER_ID}}
        WAYLAND_NAME=${{WAYLAND_DISPLAY:-wayland-0}}
        WAYLAND_SOCKET="$RUNTIME_DIR/$WAYLAND_NAME"
        PIPEWIRE_SOCKET="$RUNTIME_DIR/pipewire-0"

        if [ ! -S "$WAYLAND_SOCKET" ]; then
          printf '%s\\n' 'Wayland socket not found. Use scripts/playtest-host or configure a host GUI session first.'
          exit 2
        fi
        if [ ! -d /dev/dri ]; then
          printf '%s\\n' '/dev/dri not found. GPU passthrough is unavailable; use scripts/playtest-host.'
          exit 2
        fi
        if [ ! -S "$PIPEWIRE_SOCKET" ]; then
          printf '%s\\n' 'PipeWire socket not found. Audio passthrough is unavailable; use scripts/playtest-host.'
          exit 2
        fi
        if [ ! -d /dev/input ]; then
          printf '%s\\n' '/dev/input not found. Controller passthrough is unavailable; use scripts/playtest-host.'
          exit 2
        fi

        printf '%s\\n' 'Launching advanced sandbox GUI playtest with GPU/audio/controller passthrough.'
        printf '%s\\n' 'This intentionally exposes selected host display/audio/input interfaces to the project container.'
        podman run --rm -it \\
          --label agentkit.project={shlex.quote(project_id(config))} \\
          --label agentkit.generated=true \\
          --userns=keep-id \\
          --user "$USER_ID:$(id -g)" \\
          --env AGENTKIT_INSIDE_SANDBOX=1 \\
          --env HOME=/tmp/agentkit-home \\
          --env WAYLAND_DISPLAY="$WAYLAND_NAME" \\
          --env XDG_RUNTIME_DIR="/run/user/$USER_ID" \\
          --device /dev/dri \\
          --device /dev/input \\
          --volume "$ROOT:/workspace:Z" \\
          --volume "$WAYLAND_SOCKET:/run/user/$USER_ID/$WAYLAND_NAME:Z" \\
          --volume "$PIPEWIRE_SOCKET:/run/user/$USER_ID/pipewire-0:Z" \\
          --workdir /workspace \\
          "$IMAGE" godot --path .
        """
    )


def sandbox_readme(config: ProjectConfig) -> str:
    return clean(
        f"""
        # Agent Kit rootless Podman sandbox

        This sandbox uses rootless Podman with the project mounted at `/workspace`.
        Its explicit image profile is `{config.sandbox.image_profile}`. The image profile is a project toolchain choice and is independent of the host distribution and project target platforms.
        It reduces host filesystem risk, but it is not a magic safety boundary: untrusted code can still damage mounted project files and misuse network access when networking is enabled.

        Project containers use Podman's `--userns=keep-id` and the current host `id -u` / `id -g` so files created under `/workspace` stay owned by the real host user instead of a hard-coded container account.

        Toolchain commands default to no network. Use `AGENTKIT_SANDBOX_NETWORK=default scripts/sandbox/check`
        or `AGENTKIT_SANDBOX_NETWORK=default scripts/sandbox/exec ...` only when a reviewed task needs network access.

        Run `scripts/sandbox/*` wrappers from the host project root. Once you are already inside the container,
        run project commands directly, such as `./scripts/check.sh`, instead of launching Podman again.

        `scripts/sandbox/preflight` is the host setup gate. It uses `agent-starter` from `PATH` or `../agent-starter`
        when available; otherwise it runs the generated host-side scripts and writes `.agent-starter/sandbox/preflight.json`.
        The stamp is trustworthy only while its sandbox fingerprint matches the current generated sandbox files.
        Use `scripts/sandbox/status` to check that validity even when `agent-starter` is not on this session's `PATH`.

        `scripts/sandbox/build` reuses the existing project image by default. Run `scripts/sandbox/build --rebuild`
        when the Containerfile or toolchain package set changes.

        `scripts/sandbox/clean` removes labeled project containers. Add `--image` to remove the generated image.
        Add `--volumes --yes` only when you intentionally want to delete project cache, Codex container home,
        and dev database volumes.

        The sandbox does not mount host `~/.codex`, `~/.ssh`, browser profiles, GPG/SSH agents, GitHub credentials, production configs, or the host home directory by default.
        """
    )


def cachyos_podman_doc(config: ProjectConfig) -> str:
    return clean(
        f"""
        # CachyOS rootless Podman troubleshooting

        This project was generated for rootless Podman sandbox mode `{config.sandbox.mode}` with image profile `{config.sandbox.image_profile}`. The image choice is independent of the host distribution.

        ## Normal model

        | Thing | Runs where | Has OpenAI login? | Can access host project files? | Network default |
        |---|---|---:|---:|---:|
        | `START_AGENT.sh` | Host | Yes | Yes | Host normal |
        | `agent-starter sandbox preflight` | Host | No | Yes | Build may use network |
        | `scripts/sandbox/check` | Podman container | No | `/workspace` only | No network |
        | Host Codex default mode | Host Codex sandbox | Yes | Workspace only | Codex policy |
        | Codex-inside-container mode | Podman container | Explicit opt-in | `/workspace` only | Container policy |

        Recommended default flow:

        ```text
        host terminal
          └─ START_AGENT.sh
               ├─ scripts/sandbox/preflight
               │    ├─ doctor
               │    ├─ build image
               │    └─ check project
               ├─ write valid preflight stamp
               └─ launch Codex on host
                    └─ Codex edits project files
                         └─ Codex may run scripts/sandbox/check when approvals allow it
        ```

        Advanced opt-in flow:

        ```text
        host terminal
          └─ scripts/sandbox/codex
               └─ podman run ...
                    └─ Codex runs inside /workspace
        ```

        ## Host checks

        Review these from a normal host terminal:

        ```bash
        {CACHYOS_PODMAN_COMMAND}
        podman info
        podman run --rm docker.io/library/alpine:latest true
        grep "^$USER:" /etc/subuid /etc/subgid
        podman system migrate
        ```

        Do not run generated sandbox scripts with `sudo`. Do not try to repair rootless Podman from inside Codex
        workspace sandboxing. If `/run/user/<uid>/libpod` is read-only, missing, or permission-denied, treat it as a
        host/rootless Podman runtime environment problem, not a project code problem.

        If `/etc/subuid` or `/etc/subgid` mappings changed, `podman system migrate` may be needed. Review Podman
        documentation before running migration commands on a machine with important existing containers.

        ## Logs

        Preflight writes logs under:

        ```text
        .agent-starter/logs/sandbox-preflight-doctor.log
        .agent-starter/logs/sandbox-build.log
        .agent-starter/logs/sandbox-check.log
        ```

        These logs are intended for troubleshooting and should not contain secrets.
        """
    )


def sandbox_doc(config: ProjectConfig) -> str:
    if config.project_type == "game" or "godot" in config.languages:
        if config.sandbox.gui_passthrough:
            game_note = (
                "\nAdvanced GUI passthrough is enabled. `scripts/sandbox/playtest-gui` intentionally exposes "
                "selected host Wayland, GPU, PipeWire audio, and input/controller interfaces to the project "
                "container for interactive game playtesting. Use it only for local development workspaces and "
                "review failures carefully. Headless checks remain the preferred autonomous Codex path.\n"
            )
        else:
            game_note = (
                "\nInteractive GPU/audio/controller playtesting is usually better on the host. The sandbox is for "
                "headless checks and export/test flows. If container playtesting is required, regenerate or update "
                "the sandbox with `sandbox.gui_passthrough: true` after explicitly accepting the extra host interface exposure. "
                "For Godot projects, see `docs/GODOT-SANDBOX.md` for the `scripts/godot-headless-test.sh` hook and headless artifact guidance.\n"
            )
    else:
        game_note = ""
    mode_note = (
        "\nIn `toolchain` mode, Codex normally runs on the host and edits the project directory directly. The container boundary applies to build, test, database, and toolchain commands run through `scripts/sandbox/*`. Source files still live in the local project and are mounted into the container at `/workspace`.\n"
        if config.sandbox.mode == "toolchain"
        else "\nIn Codex-inside-container mode, use the generated `codex-login`, `codex`, and `resume` scripts only after explicit user action. Do not mount or copy host Codex auth into the container.\n"
        if config.sandbox.codex_inside_container
        else "\nIn files-only mode, these files are generated for review and are not the default execution path until a human explicitly chooses to use them.\n"
    )
    return clean(
        f"""
        # Sandbox

        This project can use a rootless Podman sandbox. Mode: `{config.sandbox.mode}`. Image profile: `{config.sandbox.image_profile}`.
        The image profile is an explicit project toolchain choice and does not have to match the host distribution or project target platforms.
        {mode_note}

        ## Safety model

        - Codex's own sandbox is still separate from the container.
        - Rootless Podman reduces host filesystem risk but does not make untrusted code magically safe.
        - The project is mounted at `/workspace`; container commands can still modify mounted project files.
        - Project containers use `--userns=keep-id` with the current host `id -u` and `id -g` so generated workspace files stay owned by the real user instead of UID 1000 or another fixed account.
        - `/home/codex` is not world-writable in the image. Codex mode uses a project-specific named volume mounted with Podman's ownership adjustment; the shared temporary toolchain home retains sticky-directory semantics.
        - Toolchain `check`, `exec`, and `shell` default to `--network none`; use `AGENTKIT_SANDBOX_NETWORK=default ...` only after review.
        - Do not mount production secrets, host `~/.codex`, SSH keys, browser profiles, or the host home directory.
        - Do not use `--dangerously-bypass-approvals-and-sandbox`.
        - Do not use host `danger-full-access` as the default answer to permission problems.

        ## Commands

        Host-side sandbox wrappers:

        ```bash
        scripts/sandbox/doctor
        scripts/sandbox/preflight
        scripts/sandbox/status
        scripts/sandbox/build
        scripts/sandbox/build --rebuild  # rebuild image after toolchain changes
        scripts/sandbox/check
        scripts/sandbox/shell
        scripts/sandbox/clean
        scripts/sandbox/clean --image
        scripts/sandbox/clean --volumes --yes
        ```

        Inside-container project commands:

        ```bash
        ./scripts/check.sh
        # or focused project commands such as npm test, python3 -m unittest, cargo test, or go test ./...
        ```

        Do not run host-side sandbox launchers from inside the container. The generated `check`, `exec`, `shell`,
        `web`, and `headless-test` helpers detect container execution and run project commands directly. Host-only
        helpers such as `build`, `codex`, `codex-login`, `resume`, `codex-exec`, and database service wrappers
        refuse to run inside the container instead of attempting nested Podman.

        Human host preflight:

        ```bash
        agent-starter sandbox preflight .
        scripts/sandbox/doctor
        scripts/sandbox/build
        ```

        Run host-side Podman wrappers from a normal host terminal before launching Codex. `agent-starter sandbox
        preflight .` writes `.agent-starter/sandbox/preflight.json` after a successful host preflight. Trust that
        file only when `agent-starter status .` reports the sandbox preflight is valid/current. If it is valid,
        an already-open constrained Codex session should not rerun
        `scripts/sandbox/doctor` or `scripts/sandbox/build`.
        If `agent-starter` is not on `PATH`, use `scripts/sandbox/status`; it delegates to `../agent-starter`
        when available or validates the stamp fingerprint itself.

        Codex may run `scripts/sandbox/check` only when its current sandbox/approval policy permits rootless
        Podman access. If a host-side wrapper fails with a Podman runtime/sandbox error from inside Codex, record
        the exact failure and use `BLOCKED_ENVIRONMENT` until the human runs the preflight/check from a normal
        host terminal or launches Codex inside the container. Do not request `danger-full-access`, host
        full-access, privileged containers, or Podman socket mounts to make these wrappers work.

        If the sandbox was requested for build/test work, do not silently fall back to host build/test commands
        when `doctor`, `build`, or `check` fails. Record the exact failure and either stop with
        `BLOCKED_ENVIRONMENT` or ask the human whether a temporary host-only fallback is acceptable.

        For Codex inside the container:

        ```bash
        scripts/sandbox/codex-login
        scripts/sandbox/codex
        scripts/sandbox/resume
        ```

        `codex-login` uses device authorization inside the project-specific Codex home volume. Do not copy host auth files into the container. Prefer a handoff summary over raw host session import.
        See `docs/CACHYOS-PODMAN.md` for rootless Podman troubleshooting and the host/container/Codex flow table.
        {game_note}
        """
    )


def autonomous_prompt(config: ProjectConfig) -> str:
    return clean(
        """
        # First-run autonomous sandbox prompt

        Use this only for disposable/local development workspaces. The sandbox is part of the requested execution boundary; do not request host full-access.

        Continue until exactly one terminal state is reached:

        - COMPLETE
        - BLOCKED_PERMISSION
        - BLOCKED_DECISION
        - BLOCKED_ENVIRONMENT
        - BLOCKED_FAILURE
        - PLAN_READY

        Work rules:

        - Do not ask for Codex `danger-full-access`, host full-access, privileged containers, or Podman socket mounts to make Podman work.
        - Host-side sandbox preflight should be run before Codex launch through `scripts/sandbox/preflight`, which uses `agent-starter` from `PATH` or adjacent `../agent-starter` when available and writes `.agent-starter/sandbox/preflight.json` after success.
        - Use `scripts/sandbox/status` to check whether preflight is valid/current, stale, missing, or failed when `agent-starter status .` is unavailable.
        - If preflight is valid/current, do not rerun `scripts/sandbox/doctor` or `scripts/sandbox/build` from inside this Codex session.
        - Use `scripts/sandbox/check` only when the current Codex sandbox/approval policy permits rootless Podman access.
        - If host-side sandbox verification is required but unavailable from this Codex session, stop with `BLOCKED_ENVIRONMENT` and tell the human to run `scripts/sandbox/preflight` or `scripts/sandbox/check` from a normal host terminal, or launch Codex inside the container.
        - If this Codex session is already inside the container, run `./scripts/check.sh` and focused project commands directly; do not run host-side `scripts/sandbox/*` launchers from inside the container.
        - Do not silently fall back to host build/test commands if `scripts/sandbox/doctor`, `scripts/sandbox/build`, or `scripts/sandbox/check` fails.
        - If the sandbox is unavailable, record the exact failure and stop with `BLOCKED_ENVIRONMENT` unless the human explicitly approves a host-only fallback.
        - Do not install host packages.
        - Do not deploy.
        - Do not rsync to production.
        - Do not create GitHub remotes or push without approval.
        - Do not mount real secrets.
        - Do not bypass Codex sandboxing.
        - Update `docs/11-IMPLEMENTATION-NOTES.md` before stopping.
        """
    )


def handoff_prompt(config: ProjectConfig) -> str:
    del config
    return clean(
        """
        # Create a Codex container handoff

        Write `docs/CODEX-HANDOFF.md` for a future Codex session that may run inside the project sandbox.

        Include:

        - current objective;
        - decisions made;
        - files changed;
        - tests and commands run with results;
        - known failures or blockers;
        - next step.
        - whether the next session is expected to run on the host or already inside the container.

        Rules:

        - Do not include OAuth tokens, API keys, cookies, passwords, device codes, SSH keys, browser profile paths, or credential file contents.
        - Do not copy raw Codex session transcripts.
        - Do not tell an inside-container session to run host-side `scripts/sandbox/*` launchers; use direct project commands such as `./scripts/check.sh`.
        - Do not reference host-only paths unless needed to explain a migration issue.
        - Prefer paths relative to the project root.
        - Keep the handoff concise enough for a new session to read before continuing.
        """
    )


def file_map(config: ProjectConfig) -> dict[str, str]:
    if not config.sandbox.enabled:
        return {}
    files = {
        ".agent-starter/sandbox/Containerfile": containerfile(config),
        ".agent-starter/sandbox/sandbox.json": sandbox_json(config),
        ".agent-starter/sandbox/README.md": sandbox_readme(config),
        "docs/CACHYOS-PODMAN.md": cachyos_podman_doc(config),
        "docs/12-SANDBOX.md": sandbox_doc(config),
        "scripts/sandbox/doctor": doctor_script(config),
        "scripts/sandbox/preflight": preflight_script(config),
        "scripts/sandbox/status": status_script(config),
        "scripts/sandbox/build": build_script(config),
        "scripts/sandbox/shell": shell_script(config),
        "scripts/sandbox/exec": exec_script(config),
        "scripts/sandbox/check": check_script(config),
        "scripts/sandbox/logs": logs_script(config),
        "scripts/sandbox/clean": clean_script(config),
        "docs/agent-prompts/create-container-handoff.md": handoff_prompt(config),
    }
    if config.sandbox.codex_inside_container:
        files.update(
            {
                "scripts/sandbox/codex": codex_script(config),
                "scripts/sandbox/codex-login": codex_login_script(config),
                "scripts/sandbox/resume": resume_script(config),
                "scripts/sandbox/codex-exec": codex_exec_script(config),
            }
        )
    files.update(db_scripts(config))
    files.update(web_script(config))
    files.update(game_scripts(config))
    if config.sandbox.first_run_autonomous_prompt:
        files["FIRST_RUN_AUTONOMOUS.md"] = autonomous_prompt(config)
    return files


def doctor_lines(root: Path) -> tuple[int, list[str]]:
    """Return sandbox doctor diagnostics without mutating the host."""
    root = root.expanduser().resolve()
    lines = [f"Agent Kit sandbox doctor: {root}"]
    code = 0
    config_path = root / ".agent-starter" / "sandbox" / "sandbox.json"
    if config_path.is_file():
        lines.append("[ok] sandbox config exists")
        try:
            config = json.loads(config_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            lines.append(f"[fail] sandbox config is invalid JSON: {exc}")
            return 2, lines
        if config.get("engine") == "podman":
            lines.append("[ok] sandbox engine: podman")
        else:
            lines.append(f"[fail] unsupported sandbox engine: {config.get('engine', 'missing')}")
            code = 2
        image = str(config.get("image") or "")
    else:
        lines.append("[fail] missing .agent-starter/sandbox/sandbox.json")
        lines.append("Generate a project with sandbox.enabled true before using sandbox commands.")
        return 2, lines

    podman = shutil.which("podman")
    if podman is None:
        lines.append("[missing] podman")
        lines.append(f"Review on CachyOS: {CACHYOS_PODMAN_COMMAND}")
        return 2, lines
    lines.append(f"[ok] podman: {podman}")

    try:
        info = subprocess.run(
            ["podman", "info", "--format", "{{.Host.Security.Rootless}}"],
            cwd=root,
            text=True,
            capture_output=True,
            check=False,
            timeout=20,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        lines.append(f"[fail] podman info did not complete: {exc}")
        return 2, lines
    if info.returncode != 0:
        detail = (info.stderr or info.stdout).strip()
        lines.append(f"[fail] podman info failed: {detail}")
        return 2, lines
    if (info.stdout or "").strip().lower() == "true":
        lines.append("[ok] Podman reports rootless mode")
    else:
        lines.append("[warn] Podman did not report confirmed rootless mode")

    try:
        help_result = subprocess.run(
            ["podman", "run", "--help"],
            cwd=root,
            text=True,
            capture_output=True,
            check=False,
            timeout=20,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        lines.append(f"[warn] could not check Podman --userns support: {exc}")
    else:
        if help_result.returncode == 0 and "--userns" in (help_result.stdout or ""):
            lines.append("[ok] Podman supports --userns=keep-id for host-owned workspace files")
        else:
            lines.append("[warn] Could not confirm Podman --userns support; workspace file ownership may need review")

    user_name = ""
    try:
        user = subprocess.run(["id", "-un"], text=True, capture_output=True, check=False, timeout=5)
        user_name = (user.stdout or "").strip() if user.returncode == 0 else ""
    except (OSError, subprocess.TimeoutExpired):
        user_name = ""
    for path in (Path("/etc/subuid"), Path("/etc/subgid")):
        if not user_name or not path.is_file():
            lines.append(f"[warn] {path} not inspectable")
            continue
        try:
            has_mapping = any(line.startswith(f"{user_name}:") for line in path.read_text(encoding="utf-8", errors="replace").splitlines())
        except OSError:
            has_mapping = False
        lines.append(f"[{'ok' if has_mapping else 'warn'}] {path} {'has' if has_mapping else 'does not show'} a mapping for this user")

    if shutil.which("pasta") or shutil.which("passt"):
        lines.append("[ok] rootless networking helper found")
    else:
        lines.append("[warn] passt/pasta not found; rootless networking may be limited")
    if shutil.which("fuse-overlayfs"):
        lines.append("[ok] fuse-overlayfs found")
    else:
        lines.append("[warn] fuse-overlayfs not found; Podman may use another storage driver")

    if image:
        image_check = subprocess.run(["podman", "image", "exists", image], cwd=root, check=False, timeout=20)
        if image_check.returncode == 0:
            lines.append(f"[ok] sandbox image exists: {image}")
        else:
            lines.append(f"[info] sandbox image needs build: scripts/sandbox/build ({image})")
    return code, lines
