"""Repository support and local-environment artifact templates."""

from __future__ import annotations

from ..models import ProjectConfig
from ..toolchains import gitignore_for, unique
from .common import clean


def render_gitignore(config: ProjectConfig) -> str:
    return "\n".join(gitignore_for(config.languages, config.database)) + "\n"


def render_rsync_excludes(config: ProjectConfig) -> str:
    lines = [
        "# Generated by CLI AI Agent Starter Kit.",
        "# Used by `agent-starter rsync-plan` to mirror source and durable docs without local runtime artifacts.",
        ".git/",
        ".agent-starter/manifest.json",
        ".agent-starter/runtime.json",
        ".agent-starter/backups/",
        ".agent-starter/proposals/",
        ".codex/*.log",
        ".codex/*.jsonl",
        ".codex/sessions/",
        ".codex/tmp/",
    ]
    for pattern in gitignore_for(config.languages, config.database):
        if pattern.startswith("!"):
            continue
        if pattern == ".env.*":
            lines.extend((".env.local", ".env.*.local", ".env.*.secret"))
            continue
        lines.append(pattern)
    return "\n".join(unique(lines)) + "\n"


def render_env_example(config: ProjectConfig) -> str:
    lines = [
        "# Copy to .env for local development only. Never commit .env.",
        "APP_ENV=development",
        "LOG_LEVEL=info",
    ]
    if config.database == "sqlite":
        lines.append("DATABASE_URL=sqlite:///data/app.sqlite3")
    elif config.database == "mariadb":
        lines.extend(("DATABASE_HOST=127.0.0.1", "DATABASE_PORT=3306", "DATABASE_NAME=app_dev", "DATABASE_USER=app_dev", "DATABASE_PASSWORD=replace-locally"))
    elif config.database == "postgresql":
        lines.extend(("DATABASE_HOST=127.0.0.1", "DATABASE_PORT=5432", "DATABASE_NAME=app_dev", "DATABASE_USER=app_dev", "DATABASE_PASSWORD=replace-locally"))
    if config.network_access:
        lines.extend(("HTTP_CONNECT_TIMEOUT_SECONDS=10", "HTTP_TOTAL_TIMEOUT_SECONDS=30"))
    return "\n".join(lines) + "\n"


def render_editorconfig() -> str:
    return clean(
        """
        root = true

        [*]
        charset = utf-8
        end_of_line = lf
        insert_final_newline = true
        indent_style = space
        indent_size = 4
        trim_trailing_whitespace = true

        [*.{js,ts,json,yml,yaml,css,html}]
        indent_size = 2

        [*.md]
        trim_trailing_whitespace = false
        """
    )
